apiVersion: v1
kind: ConfigMap
metadata:
  name: baguette-git
  namespace: baguette
data:
  config: |
      [DEFAULT]
      amqp_uri=<amqp-uri>

      [frasage]
      gitolite=/data/gitolite

      [cuisson]
      enabled=true

      [defournement]
      enabled=true
