apiVersion: v1
kind: Service
metadata:
  name: baguette-git
  namespace: baguette
  labels:
    kubernetes.io/name: baguette-git
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
  selector:
    k8s-app: baguette-git-and-build
